# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.1.0

# to run every 7 am in the morning see below. the first * is for minutes, the second is for hours, the third is for day of month, the fourth is for day of month, the fifth is for the day of the week
#nightly: 
#  triggers:
#    cron: "* 7 * * * "

#test cases commands:



jobs:

  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run:
          name: Giving permissions
          command: chmod +x mnvw 
      - run: 
          command: ./mvnw -Dmaven.test.skip=true package
  test-1:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run:
          name: Giving permissions
          command: chmod +x mnvw 
      - run: 
          command: ./mvnw test

workflows:
  version: 2.1
  build-test:
      jobs:
        - build
        - test-1:
            requires:
              - build